### ISSUE TITLE
invalid part (partNum/etag) combination for the upload

### ISSUE THREAD

**Issue by ekumen** [oracle/oci-java-sdk#95] opened 2018-12-21 09:12 UTC
Hi,
I got below exception when I use multiple uploading. The file size is about 1G, and per part is 15M.
Do anyone know what error might cause this exception? Any clue is appreciated! Thanks for your help! 

```
com.oracle.bmc.model.BmcException: (400, InvalidUploadPart, false) There were some invalid part (partNum/etag) combination for the upload UploadKey{objectKey=ObjectKey{bucket=BucketKey{namespace='intnosql', name='kvmtd-backups', api='Api{version='v2'}', bucketId='BucketId{id=HUgMO4SmQy/CzSqFKtHe63-intn-kvmt}'}, name='/andc/backups/DStore1/rg13/rn2/18122108/00004e15.jdb'}, uploadId='19fd43c7-ad01-0112-6771-3db929e83164'} (opc-request-id: 4ed0c768-c137-b3f3-be98-c2181e0afd56)
        at com.oracle.bmc.http.internal.ResponseHelper.throwIfNotSuccessful(ResponseHelper.java:92)
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:86)
        at com.oracle.bmc.http.internal.ResponseConversionFunctionFactory$ValidatingParseResponseFunction.apply(ResponseConversionFunctionFactory.java:82)
        at com.oracle.bmc.objectstorage.internal.http.CommitMultipartUploadConverter$1.apply(CommitMultipartUploadConverter.java:95)
        at com.oracle.bmc.objectstorage.internal.http.CommitMultipartUploadConverter$1.apply(CommitMultipartUploadConverter.java:83)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.commitMultipartUpload(ObjectStorageClient.java:337)
```

**Comment by andy-miles** [comment] 2019-01-07 18:06
The error you describe occurs if you are trying to commit a multipart upload if either of the following is true:

1. Not all parts have been uploaded for a given sequence range (e.g., parts 1 through 100 with part 50 not having been successfully uploaded).
2. Not all parts have been properly specified along with matching eTag values in a CommitMultipartUpload request. 

Are you using the `UploadManager` to upload objects via the multipart API?

If not, when invoking the [CommitMultipartUpload](https://docs.cloud.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/CommitMultipartUpload) API, the request must contain a list of all uploaded parts and corresponding/matching eTags.  The eTags for the parts may be obtained via the [ListMultipartUploadParts](https://docs.cloud.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/ListMultipartUploadParts).

**Comment by andy-miles** [comment] 2019-01-15 21:41
I'm closing this issue as there hasn't been a reply.  Please reopen if you continue to have issues and/or questions.

**Comment by ekumen** [comment] 2019-01-16 09:20
@andy-miles Thanks for your reply! I didn't use UploadManager. According to your reply, I guess I miss some part due to my code bug, but I'm still debugging it.
I can't use UploadManager since a file can be appended more content while it is being uploading. Also, I need to calculate the digest of uploaded file.

**Comment by ekumen** [comment] 2019-01-21 07:58
@andy-miles I can't reopen this issue. I have one more question after debugging my error.

I can upload files using multiple-upload successfully in most cases. But I found there's one case I will get above invalid part (partNum/etag) error.
Each file part is uploaded one by one. But one file part uploading has below timeout exception, 
and it successfully retried uploading this part(using the same UploadPartRequest, the same objectName, the same uploadId, the same uploadPartNum... etc). After all parts are uploaded, committing this multiple-upload will throw the invalid part (partNum/etag) error.

`com.oracle.bmc.model.BmcException: (-1, null, true) Timed out while communicating to: https://objectstorage.us-phoenix-1.oraclecloud.com (outbound opc-request-id: 99329273455A4C80B255FBC40A32FD39)
        at com.oracle.bmc.http.internal.RestClient.convertToBmcException(RestClient.java:531)
        at com.oracle.bmc.http.internal.RestClient.put(RestClient.java:354)
        at com.oracle.bmc.objectstorage.ObjectStorageClient.uploadPart(ObjectStorageClient.java:964)
        at ....
Caused by: javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:326)
        at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.put(ForwardingInvocationBuilder.java:134)
        at com.oracle.bmc.http.internal.RestClient.put(RestClient.java:351)
        ... 17 more
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
        at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1484)
        at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1482)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1481)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:399)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
        ... 29 more`

Most cases it can upload files successfully, so I think my way to set parts num and tags are correct. And I'm sure I didn't increase the part num when I retry uploading a part.
Is it possible the timeout means I was routed to another ObjectStorage server, then I got invalid part (partNum/etag) error? Or retry uploading a part can cause the error?

Thanks!

**Comment by andy-miles** [comment] 2019-01-22 18:06
Hi @ekumen.

According to the [documentation](https://docs.cloud.oracle.com/iaas/Content/Object/Tasks/usingmultipartuploads.htm), it should be fine to retry and upload an existing part number as it should overwrite the part if it exists.

Are you computing and specifying the part MD5 checksum as part of the header on each part upload?

Otherwise, I recommend to add some debug logging to output the contents of the CommitMultipartUpload request and compare against the output of ListMultipartUploadParts.
If the part numbers and associated eTags match, then I recommend to file a support request through the developer console so that we can review the service logs with a provided requestId and timestamp to help troubleshoot the issue further.

**Comment by ekumen** [comment] 2019-01-23 03:50
@andy-miles Thanks for your reply!
According to your suggestions, I compared the tags in my CommitMultipartUpload request and tags from ListMultipartUploadParts request. 
There are 64 parts in total. 2 of 64 parts etags are different between my CommitMultipartUpload request and ListMultipartUploadParts output. The other 62 parts etags are the same. And the two parts of error etags indeed have timeout exception and retried uploading. The confusing thing is there are three parts retried, one retried part etag is correct, the other two parts etags are wrong.
Is it possible something like this:
If one part the first uploading request timeout, and I do a second uploading request successfully and get an etag for this part. But then the first uploading request is executed in the server side that override the second uploading request etag. 

Thanks,
Luke

**Comment by andy-miles** [comment] 2019-01-23 18:02
The last uploaded part is the one that is recorded by Object Storage.  I recommend to confirm the order of operations by adding debug logging for every uploaded part that includes:
1. Timestamps of start and completion of the uploaded part
2. Part number
3. Retry attempt number
4. opc-request-id
5. eTag
6. MD5 checksum
7. Part size in bytes

If you confirm that the ListMultipartUploadParts does indeed return a mismatching eTag+MD5 for part(s) that were retried, then please file a support request through the developer console that includes the the above information along with your account information so we can investigate further.

While I'm not familiar with your implementation for utilizing the multipart upload APIs, a possible mitigating strategy to unblock/work-around this case includes adding logic to programmatically verify the uploaded parts vs. what is returned from ListMultipartUploadParts prior to calling CommitMultipartUpload.  If parts have mismatching eTag+MD5, then re-upload those parts until ListMultipartUploadParts matches what you expect for those part numbers.  Once it fully matches, then invoke CommitMultipartUpload.

Regardless if you implement a work-around or not, I still recommend to capture the additional logging information and file a support request.  This will help us to better understand the root cause of the issue.

Thank you,
-Andy

**Comment by andy-miles** [comment] 2019-01-29 00:31
I'm closing this issue as there hasn't been a reply. Please reopen/respond if you continue to have issues and/or questions.

**Closed by andy-miles** 2019-01-29 00:31 UTC
