### ISSUE TITLE
oci-sdk-java-objectstorage 1.30.1 is not in Maven Central; everything else is

### ISSUE THREAD

**Issue by ljnelson** [oracle/oci-java-sdk#280] opened 2021-01-29 04:20 UTC
As of this writing, [Maven Central shows the latest version of this particular artifact as being 1.30.0](https://search.maven.org/classic/#search%7Cga%7C1%7Ca%3A%22oci-java-sdk-objectstorage%22), while [many other artifacts are at version 1.30.1](https://search.maven.org/classic/#search%7Cga%7C1%7Cg%3A%22com.oracle.oci.sdk%22).  It looks to my naïve eyes like a release process died in the middle somewhere.

![Screen Shot 2021-01-28 at 8 19 21 PM](https://user-images.githubusercontent.com/80764/106231259-20f00b80-61a6-11eb-9fb9-9d6dc073e706.png)

See also #272.

**Comment by jodoglevy** [comment] 2021-01-29 19:57
Thanks for filing this @ljnelson . We are looking into this issue. There seems to be some problem with Bintray / Sonatype which we use for publishing to MavenCentral

**Comment by jaragan** [comment] 2021-02-01 14:13
if I use full java full SDK dependency (`1.30.1`), lot of child modules still at `1.30.0`.
```
<!-- https://mvnrepository.com/artifact/com.oracle.oci.sdk/oci-java-sdk-full -->
<dependency>
    <groupId>com.oracle.oci.sdk</groupId>
    <artifactId>oci-java-sdk-full</artifactId>
    <version>1.30.1</version>
</dependency>

```
Logs :-
`
 [ERROR] Failed to execute goal on project simple-project: Could not resolve dependencies for project com.example:simple-project:jar:1.0-SNAPSHOT: The following artifacts could not be resolved: com.oracle.oci.sdk:oci-java-sdk-identity:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-loadbalancer:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-objectstorage:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-resourcesearch:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-keymanagement:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-healthchecks:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-waas:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-streaming:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-monitoring:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-resourcemanager:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-ons:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-workrequests:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-limits:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-functions:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-oce:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-oda:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-integration:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-osmanagement:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-marketplace:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-nosql:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-secrets:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-vault:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-mysql:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-ocvp:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-usageapi:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-loggingingestion:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-logging:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-loganalytics:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-managementdashboard:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-sch:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-loggingsearch:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-managementagent:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-opsi:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-optimizer:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-tenantmanagercontrolplane:jar:1.30.1, com.oracle.oci.sdk:oci-java-sdk-rover:jar:1.30.1: Could not find artifact com.oracle.oci.sdk:oci-java-sdk-identity:jar:1.30.1 in central (https://repo.maven.apache.org/maven2) ->
`

**Comment by y-chandra** [comment] 2021-02-03 01:43
There was issue in syncing the repository from Bintray to MavenCentral. Please use the latest version `1.31.0` of the SDK.

**Comment by ljnelson** [comment] 2021-02-04 20:41
Thanks.  Please note that [Bintray is going away](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

**Comment by barchetta** [comment] 2021-02-05 18:15
FYI, we've picked up 1.31.0 and it's working for us.

**Comment by omkar07** [comment] 2021-03-04 19:55
@ljnelson We haven't seen this issue getting reproduced from SonaType end for Maven Central releases after version 1.30.1 release and using any latest version after 1.31.0 resolves this issue. Hence, we are closing this ticket. Thanks!

**Closed by omkar07** 2021-03-04 19:55 UTC
Labels: SDK

**Comment by jodoglevy** [comment] 2021-03-04 19:57
Also, yes we are aware Bintray is going away and are working on other solutions
