### ISSUE TITLE
Instance Principal AuthN doesn't work for Kafka

### ISSUE THREAD

**Issue by YogeeshKapila** [oracle/oci-java-sdk#322] opened 2021-07-16 17:25 UTC
I tried using the instance principal form of authentication as per the doc, but I am getting a NPE causing failed AuthN.
Not sure what I could be missing here.

Logs:

`Using SASL JAAS CONFIG - com.oracle.bmc.auth.sasl.InstancePrincipalsLoginModule required intent="streamPoolId:<id>";
java.lang.NullPointerException: null
	at com.oracle.bmc.auth.sasl.OciSaslClient.generateKeyMessage(OciSaslClient.java:99)
	at com.oracle.bmc.auth.sasl.OciSaslClient.evaluateChallenge(OciSaslClient.java:85)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:483)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:483)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:390)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:296)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:237)`

My version of com.oracle.oci.sdk is 1.36.0

It is failing in the establish connection phase
authprovider is resolving to null - in the OciSaslClient.java

1. SASL login module initializes a cache with key + auth provider combo.
2. Login module initializes, creates a  key + auth provider combo. This key is somehow not registered with the static cache.
3. SASL handshake begins for submitted job. The SASL code then tries to lookup the auth provider in cache with new key, and 
doesn’t find auth provider instance.
4. SASL handshake fails due to NPE

Any pointers would be appreciated.
Thanks.

**Comment by jodoglevy** [comment] 2021-07-20 18:51
Hi @YogeeshKapila - do you experience the same issue if you try using the latest version of the SDK?

Also - where are you running this code from? Instance principals auth only works from OCI Compute instances.

**Comment by YogeeshKapila** [comment] 2021-08-02 18:17
Hi @jodoglevy , I haven't tried with the latest sdk.
And Yes, I am using this from within OCI Compute Instances.

Are you saying that this is a known bug in the version 1.36.0.
I can try with the latest one as well

**Comment by joshunter** [comment] 2021-08-13 21:16
Hi @YogeeshKapila, thanks for raising this issue. I'm looking into reproducing it.

**Comment by joshunter** [comment] 2021-09-15 19:17
Hi @YogeeshKapila, since we have not received an update in a while and this seems to be something that works for others, I'm going to close this issue but feel free to reopen it if you're still having issues. Thanks.

**Closed by joshunter** 2021-09-15 19:17 UTC
Labels: SDK
