### ISSUE TITLE
Cannot able to create cross region Dataguard with instance principals

### ISSUE THREAD

**Issue by krishnachaitanya5** [oracle/oci-java-sdk#390] opened 2022-04-08 08:28 UTC
I am using Instance principals , db client to create a cross region , though I am setting the region in the dbclient it is not creating the DG on the cross region , but it is creating in the same region ? Does instance principals work differently for cross regions

**Comment by jodoglevy** [comment] 2022-04-08 15:48
@krishnachaitanya5 can you share a code sample which reproduces this issue? Also, if you switch to using  user principals auth (API key auth), does it work correctly? This will help determine if the cause of the issue has to do with instance principals, or not

**Comment by krishnachaitanya5** [comment] 2022-04-11 07:19
Hi @jodoglevy ,
We have tested the cross region is working from oci-cli with instance principals , its working fine
While doing from SDK we are getting this issue
"com.oracle.bmc.model.BmcException: (404, NotAuthorizedOrNotFound, false) The following tag namespaces / keys are not authorized or not found: 'oracle-tags' (opc-request-id: 983C85E491944C2F86FE35764B9A1B28/04E3F0F068ACFD90DA7B472572D10832/819306986D0B7CD2DDA3E03E79BE3664)"

Can you help us here ? 

Sample code attached below:

 BasicAuthenticationDetailsProvider provider = InstancePrincipalsAuthenticationDetailsProvider.builder().build();
        DatabaseClient dbClient = new DatabaseClient(provider);
        dbClient.setRegion(Region.US_PHOENIX_1);
 CreateCrossRegionAutonomousDatabaseDataGuardDetails crossRegionAtpDetails = createAtpDataguardRequest(compartmentId,primaryAtpId,atpName);
	        
  AutonomousDatabase crossRegionAtp = createATP(dbClient, crossRegionAtpDetails);
----------------	        
CreateCrossRegionAutonomousDatabaseDataGuardDetails.builder()
                   .cpuCoreCount(m_properties.getPropertyAsInteger(1)
                   .dataStorageSizeInTBs(1)
                   .displayName(atpName)
                   .dbName(atpName)
                   .compartmentId(compartmentId)
                   .dbWorkload(CreateAutonomousDatabaseDetails.DbWorkload.Oltp)
                   .licenseModel(CreateAutonomousDatabaseDetails.LicenseModel.LicenseIncluded)
                   .sourceId(seedId)                
                   .build();	        
---------------	 
CreateAutonomousDatabaseResponse response = dbClient
                    .createAutonomousDatabase(CreateAutonomousDatabaseRequest.builder().createAutonomousDatabaseDetails(createRequest).build());     
---------------

**Comment by krishnachaitanya5** [comment] 2022-04-12 04:27
Thanks @jodoglevy I will raise a ticket to them

**Comment by aballuri** [comment] 2022-04-26 15:45
@krishnachaitanya5 While creating a cross region standby you must pass the same tags as of the source database.

**Comment by Prachitbooks** [comment] 2022-05-27 12:18
Please provide working on how to use CreateCrossRegionAutonomousDatabaseDataGuardDetails.

**Comment by KartikShrikantHegde** [comment] 2022-11-17 16:12
Hi @krishnachaitanya5 , Looks like this issue is resolved via the support ticket. Is that a correct assumption? If so I will go ahead and close this ticket.

**Comment by KartikShrikantHegde** [comment] 2023-01-25 00:29
Closing this ticket as we haven't heard in a while. Please feel free to open the ticket if you need more info.

**Closed by KartikShrikantHegde** 2023-01-25 00:29 UTC
Labels: Database
